stages:
  - lint
  - test
  - build
  - tag
  - publish

variables:                         &default-vars
  GIT_STRATEGY:                    fetch
  GIT_DEPTH:                       100
  CARGO_INCREMENTAL:               0
  CARGO_TARGET_DIR:                "/ci-cache/${CI_PROJECT_NAME}/targets/${CI_COMMIT_REF_NAME}/${CI_JOB_NAME}"
  CI_IMAGE:                        "paritytech/ci-linux:production"
  CARGO_UNLEASH_INSTALL_PARAMS:    "--version 1.0.0-alpha.12"
  CARGO_UNLEASH_PKG_DEF:           ""
  VAULT_SERVER_URL:                "https://vault.parity-mgmt-vault.parity.io"
  VAULT_AUTH_PATH:                 "gitlab-parity-io-jwt"
  VAULT_AUTH_ROLE:                 "cicd_gitlab_parity_${CI_PROJECT_NAME}"

.publish-refs:                     &publish-refs
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_REF_NAME == "master"
    - if: $CI_COMMIT_REF_NAME =~ /^v[0-9]+\.[0-9]+.*$/              # i.e. v1.0, v2.1rc1

#### Vault secrets
.vault-secrets:                    &vault-secrets
  secrets:
    CRATES_TOKEN:
      vault:                       cicd/gitlab/$CI_PROJECT_PATH/CRATES_TOKEN@kv
      file:                        false
    GITHUB_TOKEN:
      vault:                       cicd/gitlab/$CI_PROJECT_PATH/GITHUB_TOKEN@kv
      file:                        false
    GITHUB_USER:
      vault:                       cicd/gitlab/$CI_PROJECT_PATH/GITHUB_USER@kv
      file:                        false

.rust-info-script:                 &rust-info-script
  - rustup show
  - cargo --version
  - rustup +nightly show
  - cargo +nightly --version
  - bash --version
  - sccache -s

.docker-env:                       &docker-env
  image:                           "${CI_IMAGE}"
  before_script:
    - *rust-info-script
    - ./scripts/ci/pre_cache.sh
    - sccache -s
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - api_failure
  interruptible:                   true
  tags:
    - linux-docker

.kubernetes-env:                   &kubernetes-env
  image:                           "${CI_IMAGE}"
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - api_failure
  interruptible:                   true
  tags:
    - kubernetes-parity-build

.collect-artifacts:                &collect-artifacts
  artifacts:
    name:                          "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    when:                          on_success
    expire_in:                     28 days
    paths:
      - ./artifacts/

#### stage:                        lint

fmt:
  stage:                           lint
  <<:                              *kubernetes-env
  script:
    - cargo +nightly fmt --all -- --check

clippy:
  stage:                           lint
  <<:                              *docker-env
  script:
    - cargo +nightly clippy --all --verbose

#### stage:                       test

deny:
  stage:                           test
  <<:                              *docker-env
  <<:                              *collect-artifacts
  script:
    - cargo deny check --hide-inclusion-graph -c .maintain/deny.toml
  after_script:
    - mkdir -p ./artifacts
    - echo "___Complete logs can be found in the artifacts___"
    - cargo deny check --hide-inclusion-graph 2> cargo_deny.log

test:
  stage:                           test
  <<:                              *docker-env
  script:
    - cargo test --all  --verbose

#### stage:                       build

build:
  stage:                           build
  <<:                              *docker-env
  script:
    - cargo build --no-default-features --target wasm32-unknown-unknown --verbose


#### stage:                        tag
# this stage will only create a tag in the repo, not release

tag-job:
  stage: tag
  <<:                              *kubernetes-env
  <<:                              *vault-secrets
  <<:                              *publish-refs
  script:
    - export CURRENT_TAG=$(git describe --tags --abbrev=0)
    - export PKG_VER=v$(cat Cargo.toml | grep -A 5 package] | grep version | cut -d '=' -f 2 | tr -d '"' | tr -d " ")
    - echo "Current tag $CURRENT_TAG"
    - echo "Package version $PKG_VER"
    - git config user.name "${GITHUB_USER}"
    - git config user.email "devops-team@parity.io"
    - git config remote.origin.url "https://${GITHUB_TOKEN}@github.com/paritytech/${CI_PROJECT_NAME}.git"
    - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    - if [ $CURRENT_TAG == $PKG_VER  ];
        then
          echo "Tag is up to date. Nothing to do.";
          export TAG=old;
        else
          echo "Tag was updated.";
          git tag -a $PKG_VER -m "new tag";
          git log --tags --simplify-by-decoration --pretty="format:%ci %d";
          git push origin --tags;
          export TAG=new;
        fi
    - echo "TAG=$TAG" > tag.env;
  artifacts:
    reports:
      dotenv: tag.env

#### stage:                       publish

unleash-to-crates-io:
  stage:                           publish
  <<:                              *kubernetes-env
  <<:                              *vault-secrets
  <<:                              *publish-refs
  script:
    - echo $TAG
    - if [ $TAG == "new"  ];
      then
        echo "Publishing to crates.io";
        cargo install cargo-unleash ${CARGO_UNLEASH_INSTALL_PARAMS};
        cargo unleash em-dragons --no-check --owner github:paritytech:core-devs ${CARGO_UNLEASH_PKG_DEF};
      else
        echo "Tag hasn't changed";
      fi
